# -*- coding: utf-8 -*-
"""Aula3_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PH3O5LcrRTsyWK7jxwimibHqzBdMQSd3
"""

import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn")

df = pd.read_excel("/content/drive/MyDrive/datasets/AdventureWorks.xlsx")

df.sample(10)

df.shape

df.dtypes

#Valor total das vendas
df["Valor Venda"].sum()

#Custo total
df["Custo Unitário"].mul(df.Quantidade).sum()

#Lucro total
df["Valor Venda"].sum() - df["Custo Unitário"].mul(df.Quantidade).sum()

#Tempo médio entre data de venda e data de envio agrupado por marca
df["TempoEnvio"] = (df["Data Envio"] - df["Data Venda"]).dt.days
df.groupby("Marca").TempoEnvio.mean()

df.isnull().sum()

#Lucro total de cada marca em cada ano disponível
pd.options.display.float_format = "{:20,.2f}".format
df["Lucro"] = df["Valor Venda"] - df["Custo Unitário"].mul(df.Quantidade)
df.groupby([df["Data Venda"].dt.year, "Marca"]).Lucro.sum().reset_index()

#Quantitade total de cada produto vendido
df.groupby("Produto").Quantidade.sum().sort_values(ascending=False).reset_index()

df.groupby("Produto").Quantidade.sum().sort_values().plot.barh(title="Total de Produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produto");

df.groupby(df["Data Venda"].dt.year).Lucro.sum().plot.bar(title="Título X Ano")
plt.xlabel("Ano")
plt.ylabel("Lucro");

df[df["Data Venda"].dt.year == 2008].groupby(df["Data Venda"].dt.month).Lucro.sum().plot(title="Lucro X Mês em 2008")
plt.xlabel("Mês")
plt.ylabel("Lucro");

df[df["Data Venda"].dt.year == 2008].groupby("Marca").Lucro.sum().plot.bar(title="Lucro X Marca em 2008")
plt.xlabel("Marca")
plt.ylabel("Lucro")
plt.xticks(rotation="horizontal");

df.TempoEnvio.describe().reset_index()

plt.boxplot(df.TempoEnvio);

plt.hist(df.TempoEnvio);

#Outlier
df[df.TempoEnvio == 20]

