# -*- coding: utf-8 -*-
"""Aula2_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jWCVljoUJzo5m9-foAGQtnN1WnfvZozh
"""

import pandas as pd

df1 = pd.read_excel("/content/drive/MyDrive/datasets/Aracaju.xlsx")
df2 = pd.read_excel("/content/drive/MyDrive/datasets/Fortaleza.xlsx")
df3 = pd.read_excel("/content/drive/MyDrive/datasets/Natal.xlsx")
df4 = pd.read_excel("/content/drive/MyDrive/datasets/Recife.xlsx")
df5 = pd.read_excel("/content/drive/MyDrive/datasets/Salvador.xlsx")

df = pd.concat([df1, df2, df3, df4, df5])

df.sample(10)

df.dtypes

df["LojaID"] = df["LojaID"].astype("object")

df.dropna(subset=["Vendas"], inplace=True)

df.isnull().sum()

df["Receita"] = df["Vendas"].mul(df["Qtde"])

df.sample(10)

df["Receita"].max()

df["Receita"].min()

df.nlargest(5, "Receita")

df.nsmallest(5, "Receita")

df.groupby("Cidade")["Receita"].sum()

df.sort_values("Receita", ascending=False).head(10)

df["Data"] = df["Data"].astype("int64")

df["Data"] = pd.to_datetime(df["Data"])

df.groupby(df["Data"].dt.year)["Receita"].sum()

df["Data"].min()

df["TrimestreVenda"] = df["Data"].dt.quarter

df.sample(10)

vendas_fevereiro_18 = df.loc[(df["Data"].dt.year == 2018) & (df["Data"].dt.month == 2)]

vendas_fevereiro_18

vendas_fevereiro_18.shape

df["LojaID"].value_counts(ascending=False).plot.bar()

df["LojaID"].value_counts(ascending=True).plot.barh();

df.groupby(df["Data"].dt.year)["Receita"].sum().plot.pie();

df["Cidade"].value_counts().plot.pie();

import matplotlib.pyplot as plt
df["Cidade"].value_counts().plot.bar(title="Total de vendas por cidade:", color="red");
plt.xlabel("Cidades");
plt.ylabel("Total de vendas");

#matplotlib.org
plt.style.use("ggplot")

df.groupby(df.Data.dt.month).Qtde.sum().plot(title="Produtos vendidos por mês");
plt.xlabel("Mês");
plt.ylabel("Total de produtos");
plt.legend();

df_2019 = df[df.Data.dt.year == 2019]

df_2019.sample(10)

df_2019.groupby(df_2019.Data.dt.month).Qtde.sum().plot(marker="o");
plt.xlabel("Mês");
plt.ylabel("Total de produtos vendidos");
plt.legend();

plt.hist(df.Qtde, color="green");

plt.scatter(x=df_2019.Data.dt.day, y=df_2019.Receita);
plt.savefig("dispersao.png");

