# -*- coding: utf-8 -*-
"""Aula1_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KqQjPQ_8YQj7YtquC_4b8sPunEiW7gNt
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/datasets/Gapminder.csv", sep=";")

df = df.rename(columns={"country":"Pais", "continent":"Continente", "year":"Ano", "lifeExp":"ExpectativaVida", "pop":"Populacao", "gdpPercap":"PIBPerCapita"})

df.head(10)

#linhas e colunas
df.shape

df.columns

df.dtypes

df.tail(10)

df.describe()

df["Continente"].unique()

oceania = df.loc[df["Continente"] == "Oceania"]

oceania.head(10)

oceania["Pais"].unique()

df.groupby("Continente")["Pais"].nunique()

df.groupby("Ano")["ExpectativaVida"].mean()

df["PIBPerCapita"].mean()

df["PIBPerCapita"].sum()

